CREATE OR REPLACE VIEW CUSTOMERBOOKINGS AS
    SELECT
        BK.BK_ID,
        CUS.CUS_NAME       AS CUSTOMER_NAME,
        CUS.CUS_EMAIL      AS CUSTOMER_EMAIL,
        PK.PRP_TITLE,
        PK.PRICE_PER_NIGHT,
        PO.PO_NAME         AS PROPERTY_OWNER,
        BK.CHECK_IN,
        BK.CHECK_OUT,
        BK.TOTAL_PRICE,
        BK.PAY_STATUS,
        BK.BOOK_STATUS
    FROM
        BOOKING       BK
        JOIN CUSTOMER CUS
        ON BK.CUS_ID = CUS.CUS_ID JOIN PROPERTY PK
        ON BK.PRP_ID = PK.PRP_ID
        JOIN PROPERTYOWNER PO
        ON PK.PO_ID = PO.PO_ID
    ORDER BY
        BK.BK_ID;

SELECT
    *
FROM
    CUSTOMERBOOKINGS;